import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a professional, premium, and comprehensive PDF report for a cloud project.
 * @param {Object} project - The workspace/project data
 * @param {string} diagramImage - Base64 data URL of the architecture diagram (optional)
 */
export const generateProjectReport = async (project, diagramImage) => {
    const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4',
        putOnlyUsedFonts: true
    });

    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    // --- COLOR PALETTE & THEMING ---
    const primaryColor = [6, 18, 45];     // Deep Navy
    const secondaryColor = [30, 41, 59];  // Slate 800
    const accentColor = [66, 133, 244];    // Cloudiverse Blue
    const accentLight = [232, 240, 254];  // Light Blue
    const successColor = [34, 197, 94];   // Emerald 500
    const textColor = [51, 65, 85];      // Slate 600
    const headerTextColor = [15, 23, 42]; // Slate 900
    const lightGray = [248, 250, 252];    // Slate 50

    // --- DATA EXTRACTION ---
    const state = project.state_json || {};
    const infraSpec = project.infraSpec || state.infraSpec || {};
    const provider = (state.selectedProvider || infraSpec.provider || 'Multi-Cloud').toUpperCase();
    const region = infraSpec.resolved_region?.resolved || infraSpec.region || 'Global Standard';
    const costData = project.costEstimation || state.costEstimation || {};
    const sizing = infraSpec.sizing || {};
    const requirements = infraSpec.requirements || {};
    const deployableServices = infraSpec.canonical_architecture?.deployable_services ||
        infraSpec.services_contract?.services ||
        state.services || [];

    // --- HELPER FUNCTIONS ---
    const addHeader = (title) => {
        doc.setFillColor(...primaryColor);
        doc.rect(0, 0, pageWidth, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.text("CLOUDIVERSE ARCHITECT | ENTERPRISE EDITION", margin, 12);
        doc.setFont("helvetica", "normal");
        const rightText = title || project.name || 'Architecture Report';
        doc.text(rightText.toUpperCase(), pageWidth - margin, 12, { align: 'right' });
    };

    const addFooter = (pageNum, total) => {
        const footerY = pageHeight - 15;
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
        doc.setFontSize(7);
        doc.setTextColor(148, 163, 184);
        doc.text("CONFIDENTIAL • GENERATED BY CLOUDIVERSE AI", margin, footerY);
        doc.text(`Doc Ref: CV-${project.id?.slice(0,8) || 'ARCH'}-${Date.now().toString().slice(-6)}`, pageWidth / 2, footerY, { align: 'center' });
        doc.text(`Page ${pageNum} of ${total}`, pageWidth - margin, footerY, { align: 'right' });
    };

    let yPos = 40;
    const checkPageBreak = (needed = 40) => {
        if (yPos + needed > pageHeight - 30) {
            doc.addPage();
            addHeader();
            yPos = 35;
            return true;
        }
        return false;
    };

    const addSectionHeading = (text, subtitle) => {
        checkPageBreak(35);
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...headerTextColor);
        doc.text(text, margin, yPos);
        
        doc.setDrawColor(...accentColor);
        doc.setLineWidth(1.2);
        doc.line(margin, yPos + 2, margin + 15, yPos + 2);
        
        if (subtitle) {
            doc.setFontSize(9);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(100, 116, 139);
            doc.text(subtitle, margin, yPos + 8);
            yPos += 18;
        } else {
            yPos += 14;
        }
    };

    // --- 1. PREMIUM COVER PAGE ---
    // Decorative Background
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
    
    // Abstract Pattern (Subtle)
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.1);
    doc.setLineDashPattern([2, 2], 0);
    for(let i=0; i < pageWidth; i+=20) {
        doc.line(i, 0, i, pageHeight);
        doc.line(0, i, pageWidth, i);
    }
    doc.setLineDashPattern([], 0);

    // Cover Content
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(42);
    doc.setFont("helvetica", "bold");
    doc.text("CLOUD", margin, 70);
    doc.setTextColor(...accentColor);
    doc.text("ARCHITECT", margin + 50, 70);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text("ENTERPRISE INFRASTRUCTURE SPECIFICATION", margin, 82);

    // Project Box
    doc.setFillColor(255, 255, 255, 0.05);
    doc.roundedRect(margin - 5, 140, pageWidth - (margin * 2) + 10, 60, 4, 4, 'F');
    
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    const nameLines = doc.splitTextToSize(project.name || 'Cloud Solution', pageWidth - (margin * 2));
    doc.text(nameLines, margin, 160);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(200, 200, 200);
    const coverDesc = project.description || "Automated cloud topology, cost analysis, and technical deployment roadmap.";
    const coverDescLines = doc.splitTextToSize(coverDesc, pageWidth - (margin * 2) - 10);
    doc.text(coverDescLines, margin, 175);

    // Footer Info on Cover
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(9);
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    doc.text(`REPORT ID: CV-${Math.random().toString(36).substr(2, 9).toUpperCase()}`, margin, pageHeight - 35);
    doc.text(`ISSUED ON: ${dateStr}`, margin, pageHeight - 30);
    doc.text(`CLASSIFICATION: PROPRIETARY & CONFIDENTIAL`, margin, pageHeight - 25);

    // --- 2. TABLE OF CONTENTS ---
    doc.addPage();
    addHeader("Table of Contents");
    yPos = 40;
    
    addSectionHeading("Document Structure", "Logical navigation of the technical specification");
    
    const tocItems = [
        { label: "1. Executive Summary", page: 3 },
        { label: "2. Technical Infrastructure Stack", page: 4 },
        { label: "3. Architecture Visualization", page: 5 },
        { label: "4. Traffic Flow & Security Topology", page: 6 },
        { label: "5. Financial Forecast & ROI", page: 7 },
        { label: "6. Implementation Roadmap", page: 8 }
    ];

    tocItems.forEach((item, idx) => {
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...textColor);
        doc.text(item.label, margin + 5, yPos);
        
        // Dot Leader
        const labelWidth = doc.getTextWidth(item.label);
        const dotsStart = margin + 10 + labelWidth;
        const dotsEnd = pageWidth - margin - 15;
        doc.setTextColor(200, 200, 200);
        let dots = "";
        for(let i=0; i< (dotsEnd - dotsStart)/2; i++) dots += ".";
        doc.text(dots, dotsStart, yPos);
        
        doc.setTextColor(...primaryColor);
        doc.setFont("helvetica", "bold");
        doc.text(item.page.toString(), pageWidth - margin - 5, yPos);
        yPos += 12;
    });

    // --- 3. EXECUTIVE SUMMARY ---
    doc.addPage();
    addHeader("Executive Summary");
    yPos = 35;

    addSectionHeading("Strategic Overview", "High-level summary of the cloud modernization strategy");
    
    doc.setFontSize(10.5);
    doc.setTextColor(...textColor);
    doc.setFont("helvetica", "normal");
    const workload = (infraSpec.intent?.intent_classification?.workload_type || "enterprise").toUpperCase();
    const overview = `This document outlines a high-fidelity cloud architecture optimized for ${workload} workloads on ${provider}. The design prioritizes systemic resilience, cost-efficiency, and elastic scalability. By leveraging managed cloud primitives in the ${region} region, this topology reduces operational overhead while maintaining a robust security posture.`;
    const overviewLines = doc.splitTextToSize(overview, pageWidth - (margin * 2));
    doc.text(overviewLines, margin, yPos);
    yPos += (overviewLines.length * 6) + 15;

    // Architectural Rationale (The "Why")
    addSectionHeading("Architectural Rationale", "Strategic justification for provider and pattern selection");
    const whyProvider = costData.recommendation_facts?.why || `Selection of ${provider} is driven by its dominant performance in ${infraSpec.selectedPattern || 'the requested architecture pattern'} and alignment with global delivery requirements.`;
    const whyLines = doc.splitTextToSize(whyProvider, pageWidth - (margin * 2));
    doc.setFontSize(10);
    doc.text(whyLines, margin, yPos);
    yPos += (whyLines.length * 6) + 10;

    const patternRationale = `The ${infraSpec.selectedPattern || 'Selected'} pattern was chosen to satisfy the requirements for ${requirements.stateful ? 'stateful data persistence' : 'stateless compute execution'} and ${requirements.availability_target || 'standard availability'} targets. This approach minimizes complexity while maximizing throughput.`;
    const patternLines = doc.splitTextToSize(patternRationale, pageWidth - (margin * 2));
    doc.text(patternLines, margin, yPos);
    yPos += (patternLines.length * 6) + 15;

    // Critical Performance Targets
    const kpiData = [
        ['Target Availability', requirements.availability_target || '99.9% (Standard)', 'Active-Active Multi-AZ'],
        ['Security Standard', requirements.security_level || 'Enterprise Balanced', 'Encryption at Rest/Transit'],
        ['Compliance Target', requirements.compliance?.join(', ') || 'Global Best Practices', 'SOC2/ISO Ready'],
        ['Recovery Time (RTO)', requirements.rto || '4 Hours', 'Automated Failover'],
        ['Environment Tier', (sizing.tier || 'Production').toUpperCase(), 'Optimized Resource Allocation']
    ];

    autoTable(doc, {
        startY: yPos,
        head: [['KPI Metric', 'Specification', 'Strategic Intent']],
        body: kpiData,
        theme: 'striped',
        headStyles: { fillColor: primaryColor, fontSize: 9 },
        styles: { fontSize: 9, cellPadding: 5 },
        margin: { left: margin, right: margin }
    });
    yPos = doc.lastAutoTable.finalY + 15;

    // --- 4. TECHNICAL INFRASTRUCTURE STACK ---
    doc.addPage();
    addHeader("Technical Infrastructure Stack");
    yPos = 35;

    addSectionHeading("Core Component Inventory", "Granular breakdown of provisioned cloud assets");

    if (deployableServices.length > 0) {
        const serviceTable = deployableServices.map(s => {
            const name = typeof s === 'string' ? s : (s.name || s.service_class);
            const tier = (typeof s === 'object' && s.tier) ? s.tier : (sizing.tier || 'Standard');
            const details = extractTechnicalDetails(s, state);
            const providerSvc = getProviderSpecificName(name, provider);
            return [
                { content: formatServiceName(name), styles: { fontStyle: 'bold' } },
                providerSvc,
                tier,
                details
            ];
        });

        autoTable(doc, {
            startY: yPos,
            head: [['Cloud Primitive', 'Provider Resource', 'Tier', 'Configuration Specs']],
            body: serviceTable,
            theme: 'grid',
            headStyles: { fillColor: primaryColor, textColor: 255, fontSize: 9 },
            styles: { fontSize: 8.5, cellPadding: 4 },
            columnStyles: { 3: { cellWidth: 70 } },
            margin: { left: margin, right: margin }
        });
        yPos = doc.lastAutoTable.finalY + 15;
    }

    // --- 5. ARCHITECTURE VISUALIZATION ---
    doc.addPage();
    addHeader("Architecture Visualization");
    yPos = 35;

    addSectionHeading("Logical Topology Blueprint", "Visual representation of the system architecture");

    if (diagramImage) {
        try {
            const imgProps = doc.getImageProperties(diagramImage);
            const pdfWidth = pageWidth - (margin * 2);
            const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

            // Add subtle border/frame
            doc.setDrawColor(226, 232, 240);
            doc.rect(margin - 2, yPos - 2, pdfWidth + 4, pdfHeight + 4);
            
            doc.addImage(diagramImage, 'PNG', margin, yPos, pdfWidth, pdfHeight);
            
            doc.setTextColor(148, 163, 184);
            doc.setFont("helvetica", "italic");
            doc.text("Exhibit A: High-Resolution Architecture Blueprint generated by Cloudiverse Neural Engine", pageWidth / 2, yPos + pdfHeight + 12, { align: 'center' });
            yPos += pdfHeight + 27;
        } catch (e) {
            doc.setTextColor(239, 68, 68);
            doc.text("[Image Generation Fault: Please ensure diagram is fully rendered in workspace before export]", margin, yPos);
            yPos += 10;
        }
    } else {
        doc.setFillColor(...lightGray);
        doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 60, 3, 3, 'F');
        doc.setTextColor(148, 163, 184);
        doc.setFontSize(10);
        doc.text("ARCHITECTURE DIAGRAM NOT ATTACHED", pageWidth / 2, yPos + 35, { align: 'center' });
        yPos += 75;
    }

    // Traffic Flow Table
    addSectionHeading("Traffic Engineering", "Secure ingress and internal routing protocols");
    const flows = [
        ['Edge Layer', 'WAF / CDN / DNS', 'DDoS Protection & Global Caching'],
        ['Ingress Control', 'Application Gateway', 'SSL Termination & Path-based Routing'],
        ['Service Mesh', 'Managed Compute', 'Private Subnet Isolation & mTLS'],
        ['Storage Tier', 'RDS / NoSQL / S3', 'VPC Endpoints & Data-at-Rest Encryption']
    ];
    autoTable(doc, {
        startY: yPos,
        head: [['Network Domain', 'Component', 'Policy Specification']],
        body: flows,
        theme: 'striped',
        headStyles: { fillColor: secondaryColor },
        styles: { fontSize: 8.5 },
        margin: { left: margin, right: margin }
    });

    // --- 6. FINANCIAL FORECAST & ROI ---
    doc.addPage();
    addHeader("Financial Forecast & ROI");
    yPos = 35;

    addSectionHeading("Investment Analysis", "Projected cloud expenditure and optimization forecast");

    // Summary Hero Box
    doc.setFillColor(...primaryColor);
    doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 40, 4, 4, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("TOTAL ESTIMATED MONTHLY RUN RATE (OPEX)", margin + 10, yPos + 15);
    
    doc.setFontSize(26);
    doc.setTextColor(...successColor);
    const totalCostValue = costData.recommended?.monthly_cost || costData.totalMonthlyCost || 0;
    const totalCostFormatted = costData.recommended?.formatted_cost || costData.totalMonthlyCostFormatted || `$${totalCostValue.toFixed(2)}`;
    doc.text(totalCostFormatted, margin + 10, yPos + 30);
    
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.setFont("helvetica", "normal");
    doc.text(`${provider} INFRASTRUCTURE • ${region}`, pageWidth - margin - 10, yPos + 30, { align: 'right' });
    yPos += 55;

    // Confidence Level Meter
    const confidence = costData.confidence || state.confidence || 0.85;
    const confidenceColor = confidence > 0.8 ? successColor : [245, 158, 11]; // Amber
    doc.setFontSize(10);
    doc.setTextColor(...headerTextColor);
    doc.text("Estimate Confidence Score:", margin, yPos);
    
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin + 50, yPos - 4, 100, 4, 2, 2, 'F');
    doc.setFillColor(...confidenceColor);
    doc.roundedRect(margin + 50, yPos - 4, 100 * confidence, 4, 2, 2, 'F');
    
    doc.setFont("helvetica", "bold");
    doc.text(`${Math.round(confidence * 100)}%`, margin + 155, yPos);
    yPos += 12;

    const explanation = costData.confidence_explanation || ["Estimate verified against current cloud provider rate cards."];
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...textColor);
    doc.text(`Rationale: ${explanation[0]}`, margin, yPos);
    yPos += 15;

    let services = [];
    if (costData.recommended?.services && Array.isArray(costData.recommended.services)) {
        services = costData.recommended.services;
    } else if (costData.services && Array.isArray(costData.services)) {
        services = costData.services;
    }

    if (services.length > 0) {
        autoTable(doc, {
            startY: yPos,
            head: [['Service Architecture Component', 'Category', 'Monthly Est.', 'Sizing']],
            body: services.map(s => [
                { content: formatServiceName(s.display_name || s.name), styles: { fontStyle: 'bold' } },
                s.category || 'Compute',
                s.cost?.formatted || `$${(s.cost?.monthly || s.cost || 0).toFixed(2)}`,
                s.sizing || 'Standard'
            ]),
            theme: 'grid',
            headStyles: { fillColor: secondaryColor },
            styles: { fontSize: 8.5 },
            margin: { left: margin, right: margin }
        });
        yPos = doc.lastAutoTable.finalY + 15;
    }

    // --- 7. SYSTEMIC RESILIENCE & SECURITY ---
    checkPageBreak(80);
    addSectionHeading("Systemic Resilience", "Stability metrics and fault tolerance analysis");
    
    const resilienceData = [
        ['Redundancy Level', 'High (Multi-AZ)', 'Automated failover across 3 independent availability zones.'],
        ['Data Durability', '99.999999999%', 'Managed persistence with automatic versioning and point-in-time recovery.'],
        ['Security Topology', 'Zero-Trust', 'Private subnet isolation with mTLS encrypted service-to-service communication.'],
        ['Scalability', 'Elastic / Predictive', 'Compute nodes scale horizontally based on real-time request telemetry.']
    ];

    autoTable(doc, {
        startY: yPos,
        body: resilienceData,
        theme: 'striped',
        styles: { fontSize: 8.5, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: 'bold', width: 40 }, 1: { textColor: accentColor, fontStyle: 'bold', width: 40 } },
        margin: { left: margin, right: margin }
    });
    yPos = doc.lastAutoTable.finalY + 20;

    // --- 8. IMPLEMENTATION ROADMAP ---
    doc.addPage();
    addHeader("Implementation Roadmap");
    yPos = 35;

    addSectionHeading("Deployment Strategy", "Automated provisioning and governance workflow");

    const steps = [
        ['Phase 1: Validation', 'Neural analysis of requirements and cost-benefit validation.'],
        ['Phase 2: IaC Generation', 'Synthesis of high-fidelity Terraform HCL modules (v1.5+).'],
        ['Phase 3: Provisioning', 'Execution of "terraform apply" within secure CI/CD pipelines.'],
        ['Phase 4: Monitoring', 'Deployment of cloud-native observability and telemetry stacks.'],
        ['Phase 5: Governance', 'Ongoing cost audits and security posture management (CSPM).']
    ];

    autoTable(doc, {
        startY: yPos,
        body: steps,
        theme: 'grid',
        styles: { fontSize: 9, cellPadding: 6 },
        columnStyles: { 0: { fontStyle: 'bold', width: 45, fillColor: lightGray } },
        margin: { left: margin, right: margin }
    });
    yPos = doc.lastAutoTable.finalY + 25;

    // Disclaimer Section
    doc.setFillColor(...lightGray);
    doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 35, 2, 2, 'F');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    const finalNote = "NOTICE: This technical specification is generated based on state-in-time data and AI-driven synthesis. It is intended for professional architectural review. Cloudiverse assumes no liability for infrastructure costs, security misconfigurations, or service availability post-deployment. Final implementation should be verified by a certified cloud professional.";
    const finalLines = doc.splitTextToSize(finalNote, pageWidth - (margin * 2) - 10);
    doc.text(finalLines, margin + 5, yPos + 10);

    // --- FINALIZE PAGE NUMBERS ---
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        addFooter(i, totalPages);
    }

    // Save
    doc.save(`${(project.name || 'Cloudiverse_Report').replace(/[^a-zA-Z0-9]/g, '_')}_Technical_Report.pdf`);
};

// --- HELPER FUNCTIONS ---

function formatServiceName(key) {
    if (!key) return 'Core Service';
    const map = {
        'computecontainer': 'Container Cluster (K8s/ECS)',
        'computeserverless': 'Neural Compute (Lambda/Functions)',
        'apigateway': 'Edge API Gateway',
        'relationaldatabase': 'High-Availability SQL (RDS)',
        'nosqldatabase': 'Global NoSQL Persistence',
        'objectstorage': 'Unified Object Storage',
        'cdn': 'Global Edge Delivery (CDN)',
        'loadbalancer': 'Elastic Load Balancer (L7)',
        'identityauth': 'Identity & Access Mgmt (IAM)'
    };
    return map[key.toLowerCase()] || (key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1'));
}

function getCategorization(key) {
    if (!key) return 'Core';
    const k = key.toLowerCase();
    if (k.includes('compute') || k.includes('container') || k.includes('function')) return 'Compute';
    if (k.includes('data') || k.includes('storage') || k.includes('sql')) return 'Persistence';
    if (k.includes('gateway') || k.includes('cdn') || k.includes('balancer') || k.includes('dns') || k.includes('network')) return 'Networking';
    if (k.includes('auth') || k.includes('identity')) return 'Security';
    return 'Services';
}

function extractTechnicalDetails(service, state) {
    if (typeof service === 'string') return 'Managed Platform Default';

    const parts = [];
    if (service.runtime) parts.push(service.runtime);
    if (service.instance_type || service.shape) parts.push(service.instance_type || service.shape);
    if (service.storage_size) parts.push(`${service.storage_size} GB`);
    if (service.multi_az) parts.push('Dual-AZ Resilience');

    return parts.length > 0 ? parts.join(' • ') : 'Neural-optimized configuration';
}

function getProviderSpecificName(key, provider) {
    const p = (provider || '').toLowerCase();
    const k = (key || '').toLowerCase();

    const awsMap = {
        'computecontainer': 'AWS Fargate',
        'computeserverless': 'AWS Lambda',
        'relationaldatabase': 'Amazon RDS',
        'nosqldatabase': 'Amazon DynamoDB',
        'objectstorage': 'Amazon S3',
        'cdn': 'Amazon CloudFront',
        'apigateway': 'Amazon API Gateway',
        'loadbalancer': 'AWS Application LB'
    };

    const gcpMap = {
        'computecontainer': 'Cloud Run',
        'computeserverless': 'Cloud Functions',
        'relationaldatabase': 'Cloud SQL',
        'nosqldatabase': 'Firestore',
        'objectstorage': 'Cloud Storage',
        'cdn': 'Cloud CDN',
        'apigateway': 'API Gateway',
        'loadbalancer': 'Cloud Load Balancing'
    };

    const azureMap = {
        'computecontainer': 'Azure Container Apps',
        'computeserverless': 'Azure Functions',
        'relationaldatabase': 'Azure SQL',
        'nosqldatabase': 'Cosmos DB',
        'objectstorage': 'Blob Storage',
        'cdn': 'Azure CDN',
        'apigateway': 'Azure API Mgmt',
        'loadbalancer': 'Azure Load Balancer'
    };

    if (p.includes('aws')) return awsMap[k] || 'AWS Managed Service';
    if (p.includes('gcp') || p.includes('google')) return gcpMap[k] || 'GCP Cloud Service';
    if (p.includes('azure')) return azureMap[k] || 'Azure Enterprise Service';
    
    return getCategorization(key);
}

